"""Compatibility wrapper for Word import tests and legacy callers."""

import re

import docx

import word_import


def import_dccthp(file_path: str) -> dict:
    """Import a DCCTHP Word file and return a flat legacy-style dict."""
    parsed = word_import.parse_docx(file_path) or {}
    data = parsed.get('data', parsed)
    hp = data.get('hp', data) if isinstance(data, dict) else {}

    result = {
        'trinh_do': hp.get('trinh_do', ''),
        'ten_tv': hp.get('ten_viet', hp.get('ten_tv', '')),
        'ten_ta': hp.get('ten_anh', hp.get('ten_ta', '')),
        'ma_hp': hp.get('ma', hp.get('ma_hp', '')),
        'mo_ta': hp.get('mo_ta', ''),
        'clo': data.get('clos', data.get('clo', [])) if isinstance(data, dict) else [],
        'rubrics': data.get('rubrics', []) if isinstance(data, dict) else [],
    }

    if _looks_like_course_code(result['ten_tv']) or not result['ten_tv'] or not result['ma_hp']:
        _fill_from_docx(file_path, result)
    return result


def _looks_like_course_code(value: str) -> bool:
    return bool(value and re.fullmatch(r'[A-ZĐ]{2,}\d+[A-Z0-9._-]*', str(value).strip().upper()))


def _fill_from_docx(file_path: str, result: dict):
    """Small fallback for documents generated by services.word_export_service."""
    doc = docx.Document(file_path)
    paragraphs = [p.text.strip() for p in doc.paragraphs if p.text and p.text.strip()]

    for idx, text in enumerate(paragraphs):
        upper = text.upper()
        if (not result['ten_tv'] or _looks_like_course_code(result['ten_tv'])) and 'ĐỀ CƯƠNG CHI TIẾT HỌC PHẦN' in upper:
            for candidate in paragraphs[idx + 1:idx + 4]:
                if candidate and not candidate.startswith('(') and not _looks_like_course_code(candidate):
                    result['ten_tv'] = candidate
                    break
        if not result['ten_ta'] and text.startswith('(') and text.endswith(')'):
            result['ten_ta'] = text[1:-1]

    for table in doc.tables:
        for row in table.rows:
            cells = [cell.text.strip() for cell in row.cells]
            joined = ' '.join(cells).lower()
            if not result['ma_hp'] and ('mã học phần' in joined or 'ma hp' in joined):
                for cell in cells[1:]:
                    if cell:
                        result['ma_hp'] = cell
                        break
            if not result['mo_ta'] and ('mô tả' in joined or 'description' in joined):
                for cell in cells[1:]:
                    if cell:
                        result['mo_ta'] = cell
                        break
